name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --immutable --immutable-cache --check-cache

      - run: yarn exec nx workspace-lint
      - run: yarn exec nx format:check
      - run: yarn exec nx affected --target=lint --parallel=3
      - run: yarn exec nx affected --target=test --parallel=3 --ci --code-coverage
      - run: yarn exec nx affected --target=build --parallel=3
